### ISSUE TITLE
Link for the assets

### ISSUE THREAD

**Issue by gaoypeng** [WEIRDLabUW/reality_gym#1]
Hi authors, thanks for your awesome work! I tried downloading the asset from the provided link in the readme file, but I encountered the problem: "Sorry, the file you requested does not exist." Could you update the link? Thanks in advance!

**Comment by qiuyuchen14** [comment]
Sorry about that! Not sure what happened but here's the link for the assets: https://drive.google.com/file/d/1aP6-XEzAGtmEBiDXangddSJ_IcvERlA4/view?usp=sharing, will update the readme soon.

**Comment by gaoypeng** [comment]
Thanks!
